//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BF2Statistics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpdated {
            get {
                return ((bool)(this["SettingsUpdated"]));
            }
            set {
                this["SettingsUpdated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClientPath {
            get {
                return ((string)(this["ClientPath"]));
            }
            set {
                this["ClientPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerPath {
            get {
                return ((string)(this["ServerPath"]));
            }
            set {
                this["ServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sqlite")]
        public global::BF2Statistics.Database.DatabaseEngine GamespyDBEngine {
            get {
                return ((global::BF2Statistics.Database.DatabaseEngine)(this["GamespyDBEngine"]));
            }
            set {
                this["GamespyDBEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sqlite")]
        public global::BF2Statistics.Database.DatabaseEngine StatsDBEngine {
            get {
                return ((global::BF2Statistics.Database.DatabaseEngine)(this["StatsDBEngine"]));
            }
            set {
                this["StatsDBEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ASP_UnlocksMode {
            get {
                return ((int)(this["ASP_UnlocksMode"]));
            }
            set {
                this["ASP_UnlocksMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ASP_GameHosts {
            get {
                return ((string)(this["ASP_GameHosts"]));
            }
            set {
                this["ASP_GameHosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ASP_IgnoreAI {
            get {
                return ((bool)(this["ASP_IgnoreAI"]));
            }
            set {
                this["ASP_IgnoreAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ASP_MinRoundTime {
            get {
                return ((int)(this["ASP_MinRoundTime"]));
            }
            set {
                this["ASP_MinRoundTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ASP_AwardsReqComplete {
            get {
                return ((bool)(this["ASP_AwardsReqComplete"]));
            }
            set {
                this["ASP_AwardsReqComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ASP_SmocCheck {
            get {
                return ((bool)(this["ASP_SmocCheck"]));
            }
            set {
                this["ASP_SmocCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ASP_GeneralCheck {
            get {
                return ((bool)(this["ASP_GeneralCheck"]));
            }
            set {
                this["ASP_GeneralCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int ASP_SpecialRankTenure {
            get {
                return ((int)(this["ASP_SpecialRankTenure"]));
            }
            set {
                this["ASP_SpecialRankTenure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ASP_DebugLevel {
            get {
                return ((int)(this["ASP_DebugLevel"]));
            }
            set {
                this["ASP_DebugLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ASP_MinRoundPlayers {
            get {
                return ((int)(this["ASP_MinRoundPlayers"]));
            }
            set {
                this["ASP_MinRoundPlayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseGlobalSettings {
            get {
                return ((bool)(this["UseGlobalSettings"]));
            }
            set {
                this["UseGlobalSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+fullscreen 1")]
        public string ClientParams {
            get {
                return ((string)(this["ClientParams"]));
            }
            set {
                this["ClientParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowServerConsole {
            get {
                return ((bool)(this["ShowServerConsole"]));
            }
            set {
                this["ShowServerConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeServerConsole {
            get {
                return ((bool)(this["MinimizeServerConsole"]));
            }
            set {
                this["MinimizeServerConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ServerForceAi {
            get {
                return ((bool)(this["ServerForceAi"]));
            }
            set {
                this["ServerForceAi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ServerFileMoniter {
            get {
                return ((bool)(this["ServerFileMoniter"]));
            }
            set {
                this["ServerFileMoniter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("us")]
        public string ASP_LocalIpCountryCode {
            get {
                return ((string)(this["ASP_LocalIpCountryCode"]));
            }
            set {
                this["ASP_LocalIpCountryCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastStatsServerAddress {
            get {
                return ((string)(this["LastStatsServerAddress"]));
            }
            set {
                this["LastStatsServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastLoginServerAddress {
            get {
                return ((string)(this["LastLoginServerAddress"]));
            }
            set {
                this["LastLoginServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalASPRequests {
            get {
                return ((int)(this["TotalASPRequests"]));
            }
            set {
                this["TotalASPRequests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BF2s Clone Leaderboard")]
        public string BF2S_Title {
            get {
                return ((string)(this["BF2S_Title"]));
            }
            set {
                this["BF2S_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BF2S_CacheEnabled {
            get {
                return ((bool)(this["BF2S_CacheEnabled"]));
            }
            set {
                this["BF2S_CacheEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int BF2S_LeaderCount {
            get {
                return ((int)(this["BF2S_LeaderCount"]));
            }
            set {
                this["BF2S_LeaderCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BF2S_Enabled {
            get {
                return ((bool)(this["BF2S_Enabled"]));
            }
            set {
                this["BF2S_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StatsDBConnectionString {
            get {
                return ((string)(this["StatsDBConnectionString"]));
            }
            set {
                this["StatsDBConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GamespyDBConnectionString {
            get {
                return ((string)(this["GamespyDBConnectionString"]));
            }
            set {
                this["GamespyDBConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string GamespyExtAddress {
            get {
                return ((string)(this["GamespyExtAddress"]));
            }
            set {
                this["GamespyExtAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GamespyEnableServerlist {
            get {
                return ((bool)(this["GamespyEnableServerlist"]));
            }
            set {
                this["GamespyEnableServerlist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GamespyAllowExtServers {
            get {
                return ((bool)(this["GamespyAllowExtServers"]));
            }
            set {
                this["GamespyAllowExtServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GamespyServerDebug {
            get {
                return ((bool)(this["GamespyServerDebug"]));
            }
            set {
                this["GamespyServerDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockHostsFile {
            get {
                return ((bool)(this["LockHostsFile"]));
            }
            set {
                this["LockHostsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateCheck {
            get {
                return ((bool)(this["UpdateCheck"]));
            }
            set {
                this["UpdateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HostsIcsFile")]
        public global::BF2Statistics.RedirectMode RedirectMode {
            get {
                return ((global::BF2Statistics.RedirectMode)(this["RedirectMode"]));
            }
            set {
                this["RedirectMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Leaderboard")]
        public global::BF2Statistics.Web.Bf2Stats.HomePageType BF2S_HomePageType {
            get {
                return ((global::BF2Statistics.Web.Bf2Stats.HomePageType)(this["BF2S_HomePageType"]));
            }
            set {
                this["BF2S_HomePageType"] = value;
            }
        }
    }
}
